import 'models.dart';

class CalendarData {
  static const List<WorldCupMatch> matches = [
    WorldCupMatch(id: 1, date: '11 de junio', team1: 'México', team2: 'Sudáfrica', venue: 'Estadio Ciudad de México', group: 'Grupo A'),
    WorldCupMatch(id: 2, date: '11 de junio', team1: 'Rep. de Corea', team2: 'Rep. Checa', venue: 'Estadio Guadalajara', group: 'Grupo A'),
    WorldCupMatch(id: 3, date: '12 de junio', team1: 'Canadá', team2: 'Bosnia y Herz.', venue: 'Estadio Toronto', group: 'Grupo B'),
    WorldCupMatch(id: 4, date: '12 de junio', team1: 'Estados Unidos', team2: 'Paraguay', venue: 'Estadio Los Ángeles', group: 'Grupo D'),
    WorldCupMatch(id: 5, date: '13 de junio', team1: 'Catar', team2: 'Suiza', venue: 'Estadio Bahía de San Francisco', group: 'Grupo B'),
    WorldCupMatch(id: 6, date: '13 de junio', team1: 'Brasil', team2: 'Marruecos', venue: 'Estadio Nueva York Nueva Jersey', group: 'Grupo C'),
    WorldCupMatch(id: 7, date: '13 de junio', team1: 'Haití', team2: 'Escocia', venue: 'Estadio Boston', group: 'Grupo C'),
    WorldCupMatch(id: 8, date: '13 de junio', team1: 'Australia', team2: 'Turquía', venue: 'Estadio BC Place Vancouver', group: 'Grupo D'),
    WorldCupMatch(id: 9, date: '14 de junio', team1: 'Alemania', team2: 'Curazao', venue: 'Estadio Houston', group: 'Grupo E'),
    WorldCupMatch(id: 10, date: '14 de junio', team1: 'Países Bajos', team2: 'Japón', venue: 'Estadio Dallas', group: 'Grupo F'),
    WorldCupMatch(id: 11, date: '15 de junio', team1: 'Argentina', team2: 'Irán', venue: 'Estadio Boston', group: 'Grupo H'),
    WorldCupMatch(id: 12, date: '15 de junio', team1: 'España', team2: 'Costa de Marfil', venue: 'Estadio Filadelfia', group: 'Grupo G'),
    WorldCupMatch(id: 13, date: '16 de junio', team1: 'Francia', team2: 'Ecuador', venue: 'Estadio Atlanta', group: 'Grupo I'),
    WorldCupMatch(id: 14, date: '16 de junio', team1: 'Uruguay', team2: 'Noruega', venue: 'Estadio San Diego', group: 'Grupo J'),
    WorldCupMatch(id: 15, date: '17 de junio', team1: 'Inglaterra', team2: 'Túnez', venue: 'Estadio Toronto', group: 'Grupo L'),
    WorldCupMatch(id: 16, date: '17 de junio', team1: 'Bélgica', team2: 'Nigeria', venue: 'Estadio Kansas City', group: 'Grupo K'),
    WorldCupMatch(id: 17, date: '18 de junio', team1: 'México', team2: 'Rep. de Corea', venue: 'Estadio Ciudad de México', group: 'Grupo A'),
    WorldCupMatch(id: 18, date: '19 de junio', team1: 'Canadá', team2: 'Catar', venue: 'Estadio BC Place Vancouver', group: 'Grupo B'),
    WorldCupMatch(id: 19, date: '19 de junio', team1: 'Estados Unidos', team2: 'Australia', venue: 'Estadio Seattle', group: 'Grupo D'),
    WorldCupMatch(id: 20, date: '20 de junio', team1: 'Brasil', team2: 'Haití', venue: 'Estadio San Diego', group: 'Grupo C'),
    WorldCupMatch(id: 21, date: '21 de junio', team1: 'Alemania', team2: 'Países Bajos', venue: 'Estadio Los Ángeles', group: 'Grupo E'),
    WorldCupMatch(id: 22, date: '22 de junio', team1: 'Argentina', team2: 'España', venue: 'Estadio Filadelfia', group: 'Grupo H'),
    WorldCupMatch(id: 23, date: '23 de junio', team1: 'Francia', team2: 'Uruguay', venue: 'Estadio Bahía de San Francisco', group: 'Grupo I'),
    WorldCupMatch(id: 24, date: '24 de junio', team1: 'Inglaterra', team2: 'Bélgica', venue: 'Estadio Miami', group: 'Grupo L'),
    WorldCupMatch(id: 25, date: '24 de junio', team1: 'México', team2: 'Rep. Checa', venue: 'Estadio Ciudad de México', group: 'Grupo A'),
    WorldCupMatch(id: 26, date: '24 de junio', team1: 'Sudáfrica', team2: 'Rep. de Corea', venue: 'Estadio Guadalajara', group: 'Grupo A'),
    WorldCupMatch(id: 27, date: '24 de junio', team1: 'Canadá', team2: 'Catar', venue: 'Estadio Vancouver', group: 'Grupo B'),
    WorldCupMatch(id: 28, date: '24 de junio', team1: 'Bosnia', team2: 'Suiza', venue: 'Estadio Toronto', group: 'Grupo B'),
    WorldCupMatch(id: 29, date: '25 de junio', team1: 'Brasil', team2: 'Escocia', venue: 'Estadio NY/NJ', group: 'Grupo C'),
    WorldCupMatch(id: 30, date: '25 de junio', team1: 'Marruecos', team2: 'Haití', venue: 'Estadio Boston', group: 'Grupo C'),
    WorldCupMatch(id: 31, date: '25 de junio', team1: 'EE.UU.', team2: 'Turquía', venue: 'Estadio Los Ángeles', group: 'Grupo D'),
    WorldCupMatch(id: 32, date: '25 de junio', team1: 'Paraguay', team2: 'Australia', venue: 'Estadio Seattle', group: 'Grupo D'),
    WorldCupMatch(id: 33, date: '26 de junio', team1: 'Alemania', team2: 'Japón', venue: 'Estadio Houston', group: 'Grupo E'),
    WorldCupMatch(id: 34, date: '26 de junio', team1: 'Curazao', team2: 'Países Bajos', venue: 'Estadio Dallas', group: 'Grupo E'),
    WorldCupMatch(id: 35, date: '26 de junio', team1: 'Argentina', team2: 'Costa de Marfil', venue: 'Estadio Filadelfia', group: 'Grupo G'),
    WorldCupMatch(id: 36, date: '26 de junio', team1: 'Irán', team2: 'España', venue: 'Estadio Miami', group: 'Grupo G'),
    WorldCupMatch(id: 37, date: '27 de junio', team1: 'Francia', team2: 'Noruega', venue: 'Estadio Atlanta', group: 'Grupo I'),
    WorldCupMatch(id: 38, date: '27 de junio', team1: 'Ecuador', team2: 'Uruguay', venue: 'Estadio San Diego', group: 'Grupo I'),
    WorldCupMatch(id: 39, date: '27 de junio', team1: 'Inglaterra', team2: 'Nigeria', venue: 'Estadio Kansas City', group: 'Grupo L'),
    WorldCupMatch(id: 40, date: '27 de junio', team1: 'Túnez', team2: 'Bélgica', venue: 'Estadio Toronto', group: 'Grupo L'),
  ];
}
